apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa-actions
  template:
    metadata:
      labels:
        app: rasa-actions
    spec:
      containers:
        - name: rasa-actions
          image: your_rasa_actions_image:latest
