apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
  template:
    metadata:
      labels:
        app: rasa
    spec:
      containers:
        - name: rasa
          image: your_rasa_image:latest
          ports:
            - containerPort: 5005
