# Use a imagem base do Elasticsearch
FROM docker.elastic.co/elasticsearch/elasticsearch:7.10.0

# Configurações específicas do Elasticsearch, se necessário
# COPY elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

# Exponha as portas necessárias
EXPOSE 9200 9300

# Comando para iniciar o Elasticsearch
CMD ["elasticsearch"]